version: "3"

services:

  nginx:
    image: 290527213425.dkr.ecr.ap-east-1.amazonaws.com/tempate-api_nginx:latest
    build:
      context: ./
      dockerfile: .docker/nginx/Dockerfile
    restart: always
    depends_on:
      - php

  php:
    image: 290527213425.dkr.ecr.ap-east-1.amazonaws.com/tempate-api_php:latest
    env_file:
      - .env
    build:
      context: ./
      dockerfile: .docker/php/Dockerfile
    restart: always
