version: "3"

services:

  nginx:
    image: 290527213425.dkr.ecr.ap-east-1.amazonaws.com/hii-berben-api_nginx:testing
    build:
      cache_from:
        - 290527213425.dkr.ecr.ap-east-1.amazonaws.com/hii-berben-api_nginx:testing
    depends_on:
      php:
        condition: service_healthy

  php:
    container_name: test-php
    image: 290527213425.dkr.ecr.ap-east-1.amazonaws.com/hii-berben-api_php:testing
    build:
      cache_from:
        - 290527213425.dkr.ecr.ap-east-1.amazonaws.com/hii-berben-api_php:testing
      context: ./
      dockerfile: .docker/php/Dockerfile.dev
    volumes:
      - ./phpunit.xml.dist:/var/www/html/phpunit.xml
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_ENV=testing
      - APP_KEY=base64:4VbqypIKk3mv9eG1UvqnwshBuIh2IPOJ5+XtIVjajYY=
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=berben_testing
      - DB_USERNAME=berben
      - DB_PASSWORD=testing
    healthcheck:
      test: test -e "/var/www/html/ready"
      interval: 2s
      timeout: 1s
      retries: 30
      start_period: 10s

  db:
    image: mariadb:testing
    build:
      cache_from:
        - mariadb:testing
      context: ./
      dockerfile: .docker/mariadb/Dockerfile
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MYSQL_DATABASE=berben_testing
      - MYSQL_USER=berben
      - MYSQL_PASSWORD=testing
    healthcheck:
      test: echo "show tables from berben_testing" | mysql -ppassword
      interval: 2s
      start_period: 10s
      timeout: 1s
      retries: 30
