version: "3"

services:

  nginx:
    image: 290527213425.dkr.ecr.ap-east-1.amazonaws.com/tempate-api_nginx:demo
    build:
      context: ./
      dockerfile: .docker/nginx/Dockerfile

  php:
    image: 290527213425.dkr.ecr.ap-east-1.amazonaws.com/tempate-api_php:demo
    env_file: .env
    build:
      context: ./
      dockerfile: .docker/php/Dockerfile
