version: "3"

services:

  nginx:
    image: 290527213425.dkr.ecr.ap-east-1.amazonaws.com/hii-berben-api_nginx:staging
    networks:
      - default
      - web

  php:
    image: 290527213425.dkr.ecr.ap-east-1.amazonaws.com/hii-berben-api_php:staging
    networks:
      - default
      - db

networks:

  web:
    external: true
    name: web

  db:
    external: true
    name: db
