name: demo_deployment

on:
  push:
    tags:
      - v**-demo

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: authenticate docker
        run: |
          aws configure set aws_access_key_id "${{ secrets.AWS_ID }}"
          aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET }}"
          aws configure set region ap-east-1
          docker login --username AWS --password $(aws ecr get-login-password --region ap-east-1) 290527213425.dkr.ecr.ap-east-1.amazonaws.com

      - name: build image
        run: |
          cp .env.example .env
          mv docker-compose.demo.yml docker-compose.override.yml
          docker-compose pull -q
          docker-compose build

      - name: push image
        run: |
          docker-compose push

      - name: setup key
        run: |
          key=$(mktemp)
          echo "key=$key" >> $GITHUB_ENV
          echo "${{ secrets.STAGING_KEY }}" > $key

      - name: deploy
        run: |
          ssh -i ${{ env.key }} -o StrictHostKeyChecking=no \
          ${{ secrets.STAGING_USER }}@${{ secrets.STAGING_HOST }} \
          " \
            cd ${{ github.event.repository.name }}-demo && \
            docker login --username AWS --password $(aws ecr get-login-password --region ap-east-1) 290527213425.dkr.ecr.ap-east-1.amazonaws.com && \
            docker-compose pull && \
            docker-compose up -d \
          "
